import type { Metadata } from "next";
import { Inter, Geologica } from "next/font/google";
import Providers from "@/providers";
import "./globals.css";

import PhotoGrid from "@/components/PhotoGrid";
import Cursor from "@/components/Cursor";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const geologica = Geologica({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${geologica.className}`}>
        <div className="min-h-screen bg-stone-900 prose-headings:font-mono overflow-hidden prose-headings:text-lime-400  selection:bg-lime-300 selection:text-lime-900 text-white prose-headings:font-medium">
          {/* <Navbar /> */}
          <Cursor />

          <div className="relative flex z-10 mx-auto justify-center flex-col lg:flex-row space-x-8 container max-w-4xl items-center w-full">
            <div className="h-96 lg:h-screen overflow-hidden lg:max-w-lg w-full dark:bg-gray-800 dark:text-white">
              <PhotoGrid />
            </div>
            <div className="min-h-screen">
              <Providers>{children}</Providers>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
